export const MessageErrors = Object.freeze({
    Required : 'Field is required.',
    Name_Max : 'Max of 30 characters.',
    Name_Pattern : 'Only words and spaces.',
    PhoneNumber_Max : 'Max of 15 characters.',
    PhoneNumber_Pattern : 'It is not an Mobile Number.',
    Zipcode_Max : 'Max of 50 characters.',
    Address_Max : 'Max of 150 characters.',
    AddressNumber_Max : 'Max of 5 characters.',
    License_Max: 'Max of 10 characters.',
    Email_Max: 'Max of 30 characters.',
    Email_Pattern: 'It is not an email.',
    Description_Max: 'Max of 150 characters.',
    Note_Max: 'Max of 150 characters.',
    DeliveryDescription_Max: 'Max of 100 characters.',
    DeliveryType_Max: 'Max of 50 characters.',
    Min: 'Can not be less than 1.',
    Time_Min: 'The allowed dates are today and tomorrow.',
    Time_Pattern: 'Invalid time.',
    Password_Min: 'Min of 7 characters.',
    Password_Pattern: 'The password should have a minuscule, a capital letter and a special character.',
    Password_Match: 'Password do not match.',
});
  